poll_answer/urls.py
from django.urls import path, include
from . import views

app_name = "answer"

urlpatterns = [
    path("save/<int:id>", views.save_answer, name="save")
]

polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'
urlpatterns = [
    path("", views.list_polls, name="list"),
    path("enquete/<int:id>", views.poll, name="poll")
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("polls.urls")),
    path("answer", include("poll_answer.urls"))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

poll_answer/models.py
from django.db import models
from polls.models import Polls, Options
# Create your models here.
class Answers_poll(models.Model):
    email_user = models.EmailField()
    answers = models.ForeignKey(Options, on_delete=models.CASCADE)
    poll = models.ForeignKey(Polls, on_delete=models.CASCADE, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "{} Respondeu {} na {} ".format(self.email_user, self.answers.option, self.poll.title)

polls/models.py
from django.db import models
from django_quill.fields import QuillField
from django.utils.html import mark_safe

# Create your models here.
class Options(models.Model):
    option = models.CharField(max_length=20)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.option

class Polls(models.Model):
    title = models.CharField(max_length=255)
    description = QuillField(null=True)
    is_published = models.BooleanField(default=False)
    options = models.ManyToManyField(Options)
    cover = models.ImageField(upload_to="covers/", blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    @property
    def cover_preview(self):
        if self.cover:
            return mark_safe("<img src='{}' width='300px' height='300px'/>".format(self.cover.url))
        return ""
    def __str__(self):
        return self.title

poll_answer/views.py
from django.shortcuts import render
import django.http as http
from django.contrib import messages
from .models import Answers_poll
from polls.models import Options, Polls
# Create your views here.

def save_answer(request: http.HttpRequest, id):
    if request.method != "POST":
        return http.HttpResponseNotAllowed(["GET"])

    data = request.POST

    email = data.get("email")
    answer = data.get("answer")
    poll_id = id
    if email is None:
        messages.add_message(request, messages.ERROR, "O campo e-mail é obrigatório", extra_tags="danger")
    if answer is None:
        messages.add_message(request, messages.ERROR, "É necessário selecionar uma resposta", extra_tags="danger")

    if poll_id is None:
        messages.add_message(request, messages.ERROR, "Enquete é obrigatória", extra_tags="danger")

    if None in [email, answer, poll_id]:
        return http.HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))

    option_model = Options.objects.filter(id=answer).first()
    if option_model is None:
        messages.add_message(request, messages.ERROR, "Opção id {} não existe".format(answer), extra_tags="danger")
        return http.HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))

    poll_model = Polls.objects.filter(id=poll_id).first()

    if poll_model is None:
        messages.add_message(request, messages.ERROR, "Enquete id {} não existe".format(poll_id), extra_tags="danger")
        return http.HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))
    

    new_answer = Answers_poll(
        email_user=email,
        answers= option_model,
        poll=poll_model)
    new_answer.save()
    
    messages.add_message(request, messages.SUCCESS, "Resposta enviada com sucesso", extra_tags="success")

    return http.HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))

polls/views.py
from django.shortcuts import render
from .models import Polls
from poll_answer import models
# Create your views here.
def list_polls(request):
    polls = Polls.objects.all().order_by("-id")
    return render(request, "polls/polls.html", context={
        "polls": polls
    })
    
def poll(request, id):
    poll = Polls.objects.filter(id=id).first()

    TOTAL_VOTOS = 0

    TOTAL_VOTOS = models.Answers_poll.objects.filter(poll=poll).count()

    options = []

    for option in poll.options.all():
        votos_questao = models.Answers_poll.objects.filter(poll=poll, answers=option).count()
        options.append({
            "option": option,
            "per_votos": (100 * votos_questao) / TOTAL_VOTOS
        })

    return render(request, "polls/poll.html", context={
        "poll": poll,
        "poll_id": id,
        "options": options
    })

polls/templates/polls/partials/card.html
<div class="card" style="width: 18rem;">
    {% if poll.cover %}
        <img src="{{poll.cover.url}}" style="height: 250px;" class="card-img-top" alt="...">
    {% endif %}
    <div class="card-body">
      <h5 class="card-title">{{ poll.title | title | slice:"0:25" }}...</h5>
      <p class="card-text">
        {{ poll.description.html | striptags |slice:"0:30" }}...
      </p>
      <a href="{% url "polls:poll" poll.id %}" class="btn btn-dark">Visualizar enquete</a>
    </div>
  </div>     

polls/templates/polls/poll.html
{% extends "global/base.html" %}

{% block "content" %}
<div class="w-100">
    {% if poll.cover %}
        <img src="{{ poll.cover.url }}" style="width: 100%; height: 70vh; object-fit: cover;"/>
    {% endif %}
</div>
<div class='container mt-5'>
    <h1> {{ poll.title }} </h1>
    {% if poll.description %}
        {{ poll.description.html | safe }}
    {% endif %}

    <hr/>
    <form method="POST" id="form_answer" action="{% url "answer:save" poll_id %}">
        {% csrf_token %}
        <input type="hidden" name="email"/>
        <div class="row">
            {% for data in options %}
                <div class="col-12 mt-2">
                    <input name="answer" type="radio" class="btn-check" name="options-outlined" id="poll-{{data.option.id}}" value="{{data.option.id}}" option-value="{{data.option.option}}" autocomplete="off">
                    <label option-check class="btn btn-outline-secondary w-100" for="poll-{{data.option.id}}">
                        {{data.option.option}} | {{data.per_votos}}
                    </label>            
                </div>
            {% endfor %}
        </div>
    </form>
    <hr/>
    <button class='btn btn-success' id='buttonEnviarRes' disabled>Enviar resposta</button>

    {% if messages %}
        {% for message in messages %}
            {% if message.tags %}
                <div class="alert alert-{{message.tags}} m-2">
                    {{message}}
                </div>
            {% else %}
                <div class="alert m-2">
                    {{message}}
                </div>
            {% endif %}

        {% endfor %}
    {% endif %}
</div>

<div class="modal" tabindex="-1" id="confirm_answer">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Enviar resposta</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <p>Tem certeza que deseja enviar essa resposta: <strong id="my_answer"></strong></p>
          <hr/>
          <label>Seu e-mail*</label>
          <input type="text" class="form-control" id="email" name="e-mail"/>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
          <button type="button" class="btn btn-success" id="sendAnswer">Enviar resposta</button>
        </div>
      </div>
    </div>
  </div>
  

{% endblock %}

{% block 'postscript' %}
<script>
    const options = document.querySelectorAll("[option-check]");
    const button = document.querySelector("#buttonEnviarRes");
    const my_answer = document.querySelector("#my_answer");
    const modal = new bootstrap.Modal('#confirm_answer')
    const buttonSendAnswer = document.querySelector("#sendAnswer");
    const form = document.querySelector("#form_answer");
    for(option of options) {
        console.log(option)
        option.addEventListener("click", () => {
            button.disabled = false;
        });
    }

    button.onclick = () => {

        let answer = document.querySelector("input[name='answer']:checked");

        my_answer.innerHTML = answer.getAttribute("option-value");

        modal.show();
    }

    buttonSendAnswer.onclick = () => {
        let email = document.querySelector("#email")
        if(email.value.length == 0) {
            return alert("O campo e-mail é obrigatório");
        }
        document.querySelector("input[name='email']").value = email.value;
        form.submit();
    }

</script>
{% endblock %}

polls/templates/polls/polls.html
{% extends "global/base.html" %}

{% block "content" %}
<div class='container mt-5'>
    <div class="row">
        {% for poll in polls %}
            <div class="col-lg-4">
                {% include 'polls/partials/card.html' %}
            </div>
        {% empty %}
            <h1>Nenhuma enquete registrada</h1>
        {% endfor %}
    </div>
</div>
{% endblock %}